name: flutter_contentvault
description: A multi-platform content archive app built with Flutter

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  # Database
  drift: ^2.14.1
  sqlite3_flutter_libs: ^0.5.18
  path_provider: ^2.1.1
  path: ^1.8.3

  # Navigation
  go_router: ^12.1.3

  # Dependency Injection
  get_it: ^7.6.4

  # Network
  dio: ^5.4.0
  retrofit: ^4.0.3
  json_annotation: ^4.8.1

  # UI Components
  cupertino_icons: ^1.0.6

  # Utils
  uuid: ^4.2.1
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.2
  share_plus: ^7.2.2

  # HTML parsing
  html: ^0.15.4
  
  # HTTP client for metadata extraction
  http: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting
  flutter_lints: ^3.0.1

  # Code generation
  build_runner: ^2.4.7
  drift_dev: ^2.14.1
  retrofit_generator: ^8.0.4
  riverpod_generator: ^2.3.9
  json_serializable: ^6.7.1

  # Testing
  mockito: ^5.4.4
  
  # App Icons
  flutter_launcher_icons: ^0.13.1
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/

  # Fonts
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/PretendardVariable.ttf

# App Icons Configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/app_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true 